plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - old_website/cg_codebase.md
  - old_website/AboutMe.md
  - old_website/excerpts.md
  - old_website/MagicalBlog.md
  - old_website/MagicalBlog_hidden.md
  - old_website/iiith/rrc/writeup_3126.md
  - iiith/courses/pois/endsem_solutions.md

markdown: kramdown
kramdown:
  math_engine: mathjax
